### ISSUE TITLE
change maven-invoker to 2.2

### ISSUE THREAD

**Issue by alexlehm** [dazraf/vertx-hot#28]
maven-invoker 2.1.1 has a bug where it fails to find the maven start script in Windows (since it is called mvn.cmd and not mvn.bat anymore), this is fixed in 2.2. Could you please update the version?

**Comment by dazraf** [comment]
Thanks for raising this. Will do it. I've been a bit busy with the day job. Will be gettting some quality time to finish off your issues Alexander. 

regards
Fuzz

**Comment by dazraf** [comment]
Released as part of 2.1.0.
