### ISSUE TITLE
Support for Buck

### ISSUE THREAD

**Issue by illuminace** [dazraf/vertx-hot#32]
I've been playing around with [Buck](https://github.com/facebook/buck), and found myself seeking the same sort of Vertx hot deploy functionality that you've developed here. 

Since the majority of this hot deploy logic is common across build tools, I'm simply [extending](https://github.com/illuminace/vertx-hot/tree/feature/buck-support) vertx-hot to support both Maven and Buck build tools. This involves splitting the plugin module into 3: core, maven and buck, ultimately producing two artefacts of interest: vertx-hot-maven-plugin and vertx-hot-buck.

By integrating Buck functionality into this project, it can leverage the same underlying logic for directory watches and VertX redeployment. In time, it could be extended to support other build tools too. However, there's undoubtedly a significant interest gap between those who'd be interested in the Maven plugin, and those who'd be interested in using Buck, so I see a perfectly valid counter-argument: that an alternative build system with very limited interest shouldn't drive the design of a plugin for the majority of users.

What are your thoughts?

Cheers

**Comment by dazraf** [comment]
I think this is a great idea! 

The refactoring will make sense even without Buck - improving clarity of the design. 

We probably will need to think about how the HitDeployParameters will work ... 

Great stuff!

**Comment by illuminace** [comment]
The basic refactoring is in place here if you want a quick peek: https://github.com/illuminace/vertx-hot/tree/feature/buck-support. I still have quite a bit of work to do on the Buck side though.

**Comment by illuminace** [comment]
Naturally welcome any ideas you have. I suppose I should really shift the branch into this repo so it can be collaborated on...

**Comment by dazraf** [comment]
thanks for branch. reading thinking in the middle of family stuff :-)
yeah, +1 for moving the branch in this repo.

some other random thoughts in my head:
. perhaps could have an organisation that this module could move under .. it's quite a pain to do this but perhaps worthwhile
. would be great to have some kind of chat tool for when g/h comments are not enough

**Comment by illuminace** [comment]
Merged to [buck-support](https://github.com/dazraf/vertx-hot/tree/feature/buck-support).

Indeed, I had similar thoughts regarding the org; perhaps something along the lines of `io.dazraf.vertx-hot`?

There is always [Gitter](https://gitter.im) for public chat (not that I've used it yet). Anyway, I've created a public room for this repo and added you, so we can give it a go at some juncture.

**Comment by dazraf** [comment]
Nice thanks for Gitter!

**Comment by dazraf** [comment]
Wondering if hot deploy params could be generalised in any way ... or perhaps the relationship between the deployment parameters and the compiler can be encapsulated in some way - that coupling could be setup by specific strategy for the build system. Hmm ...

**Comment by illuminace** [comment]
The deployment params definitely need some TLC. I still need to flesh out exactly which configuration parameters are likely to be required for Buck (my particular Buck use-case is uber-simple, and most likely won't reflect other peoples' usage). Whilst this is WIP, we should be able to figure out some structure now I guess.
- We know we have params that are required across build-tools, and some params that are specific to the build tool's `Compiler` (+ `PathsSupport` is still up in the air). 
- Getting pedantic, I suppose we could further distinguish between build params and Vertx params, though that's tenuous and I'm not sure it adds anything. 
- `HotDeploy` is a bit of a God-class at present, responsible for building all its tools and handling workflow. There's probably an argument to reduce its workload.

So...  we could have a `CommonHotDeployParams`, which would feature on the constructor signatures of `HotDeploy` & `PathsSupport`, and tool-specific versions such as `MavenHotDeployParams` that get passed to the compilers (which would include a ref to their Common siblings). 

Adding a `MavenHotDeployBuilder`/`Factory`/... to build the appropriate `Compiler`, `VerticleDeployer`, `PathsSupport` etc, and wire them in to a freshly baked `HotDeploy`, would free `HotDeploy` itself to concern itself with workflow (and would feel _marginally_ more like DI).

That should get us some of the way, with the builders responsible for wiring, and the various components receiving appropriate parameter configurations. 

That doesn't feel like it'll cure all our ailments though - suggestions most welcome! 

`PathsSupport` is likely to need some reworking too.

**Comment by illuminace** [comment]
I tried a few different approaches to tidy the structure, but didn't arrive at anything I was completely happy with. What's in now feels a bit better, but has its share of niggles. Feel free to have a play around & come up with something a bit nicer.

Will make some time to work on Buck integration in the next day or so (I'd rather not leave this branch unmerged for too long given the degree of restructuring).
