### ISSUE TITLE
Awesome project... alive?

### ISSUE THREAD

**Issue by MTyson** [dazraf/vertx-hot#36]
This is an awesome project.  Are you still working on it?

**Comment by dazraf** [comment]
Hello! Yes definitely alive :-) a bit busy at work and preparing for arrival of second child. There's a couple issues I want to raise and fix before doing another release. Also considering making the project and organisation.

**Comment by MTyson** [comment]
great to hear! Congrats on the baby!

**Comment by dazraf** [comment]
Its gonna be interesting balancing it all. 
There's so much that would be great for this project.
- Bug fixes for SSL
- web component support
- other build systems specially gradle 
- perhaps a (common) fast core build system
  Always happy to hear any feedback and commits are most welcome!

**Comment by MTyson** [comment]
@dazraf What does "perhaps a (common) fast core build system" mean?  That sounds tantalizing...
