### ISSUE TITLE
Whats in config.json?

### ISSUE THREAD

**Issue by jymboche** [dazraf/vertx-hot#4]
Thanks for this! Just started using Vertx and this was the first/easiest solution that seems to work for me.

I cant seem to find anything on a json config file. What are the options for this file? I created a file with an empty json file and it seems to run without error.

**Comment by dazraf** [comment]
Hello!
Thanks for the question. Hopefully I've understood it correctly.

### Background on Vert.x Verticles and Verticle config files

A vert.x container runs verticles (they can be thought of as micro services). 
Starting a verticle is fairly simple. See the [docs](http://vertx.io/docs/vertx-core/java/#_verticles)

A verticle can be [started with a config file](http://vertx.io/docs/vertx-core/java/#_passing_configuration_to_a_verticle). The contents of that config file is entirely decided by the verticle developer. It can contain anything. 

The plugin just gives a way of referencing such a config file, if the developer has one. In the plugin config xml, you can have any of the following:

``` xml
<configuration>
  <verticleClassName>MyVerticle</verticleClassName>
  <configFile>myconfig.json</configFile>
</configuration>
```

or 

``` xml
<configuration>
  <verticleClassName>MyVerticle</verticleClassName>
</configuration>
```

or

``` xml
<configuration>
  <verticleClassName>MyVerticle</verticleClassName>
  <configFile></configFile>
</configuration>
```

Does that help?
regards

**Comment by dazraf** [comment]
I've closed this for now. Let me know if any further questions.
